{% set name = "openidc_client" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openidc-client-{{ version }}.tar.gz
  sha256: 680e969cae18c30adbddd6a087ed09f6a296b4937b4c8bc69be813bdbbfa9847

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests

test:
  imports:
    - openidc_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/puiterwijk/python-openidc-client
  summary: OpenID Connect Client with caching and token management
  license: MIT
  license_file: COPYING

extra:
  recipe-maintainers:
    - pkgw
